// backend/src/constants/defaultTemplates.js
// Factory default templates for Instagram Automation Cards & Replies

const DEFAULT_TEMPLATES = [
  {
    id: 'ecom-discount-drop',
    name: 'Exclusive Promo Code & Discount Drop',
    category: 'ecommerce',
    categoryLabel: '🛍️ E-Commerce',
    badge: '🔥 Highest Conversion',
    trigger_keyword: 'DISCOUNT',
    match_mode: 'contains',
    action_type: 'comment',
    comment_reply_mode: 'both',
    require_follow: false,
    description: 'Instantly delivers a visual discount card to shoppers who comment on your product or sale reel.',
    comment_reply_message: 'Sent your 20% OFF code in DM! 🚀 | Check your inbox for the discount card! 📩 | Card sent! Check DMs ✨',
    dm_reply_message: "Hey {username}! 🎁 Here is your exclusive 20% discount code: VIP20\n\nValid on our entire collection for the next 24 hours only!",
    card_enabled: 1,
    card_title: '🎁 Exclusive 20% Discount Code: VIP20',
    card_subtitle: 'Use code VIP20 at checkout for 20% off your entire order today only!',
    card_image_url: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&auto=format&fit=crop&q=80',
    card_button_text: 'Shop 20% Off 🛍️',
    card_button_url: 'https://airvix.com/demo/shop',
    stats: '94% Open Rate • 38% CTR',
  },
  {
    id: 'ecom-product-catalog',
    name: 'Curated Lookbook & Best-Sellers Catalog',
    category: 'ecommerce',
    categoryLabel: '🛍️ E-Commerce',
    badge: '🛍️ Product Showcase',
    trigger_keyword: 'CATALOG',
    match_mode: 'contains',
    action_type: 'comment',
    comment_reply_mode: 'both',
    require_follow: false,
    description: 'Sends your full digital seasonal catalog as a rich visual card directly to interested shoppers.',
    comment_reply_message: 'Catalog card sent to your DM! 📖 | Lookbook in your inbox! 📩 | Check your DMs for the full collection! ✨',
    dm_reply_message: "Hey {username}! 📖 Here is our new seasonal Lookbook & Catalog with free domestic shipping on orders over $50!",
    card_enabled: 1,
    card_title: '📖 New Season Lookbook & Catalog',
    card_subtitle: 'Browse 40+ trending seasonal styles, sizing specs, and runway picks.',
    card_image_url: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&auto=format&fit=crop&q=80',
    card_button_text: 'Open Catalog 👗',
    card_button_url: 'https://airvix.com/demo/catalog',
    stats: '88% Open Rate • 44% CTR',
  },
  {
    id: 'ecom-size-guide',
    name: 'Product Size & Fit Consultation',
    category: 'ecommerce',
    categoryLabel: '🛍️ E-Commerce',
    badge: '⚡ Reduces Returns',
    trigger_keyword: 'SIZE',
    match_mode: 'contains',
    action_type: 'comment',
    comment_reply_mode: 'both',
    require_follow: false,
    description: 'Delivers detailed measurements and height/weight fit recommendations to prevent cart abandonment.',
    comment_reply_message: 'Sizing chart sent to your DM! 📏 | Check your inbox for the fit guide card! 📩',
    dm_reply_message: "Hey {username}! 📏 Here is the complete size & fit breakdown for this collection.",
    card_enabled: 1,
    card_title: '📏 Product Size & Measurement Guide',
    card_subtitle: 'Find your perfect size with our interactive height/weight sizing matrix.',
    card_image_url: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=800&auto=format&fit=crop&q=80',
    card_button_text: 'View Size Chart 📐',
    card_button_url: 'https://airvix.com/demo/size-guide',
    stats: '91% Open Rate • 29% Conversion',
  },
  {
    id: 'edu-free-pdf-guide',
    name: 'Free Masterclass Guide & Cheat Sheet PDF',
    category: 'education',
    categoryLabel: '🎓 Coaches & Creators',
    badge: '🔥 Viral Lead Magnet',
    trigger_keyword: 'GUIDE',
    match_mode: 'contains',
    action_type: 'comment',
    comment_reply_mode: 'both',
    require_follow: true,
    follow_prompt_message: "Hey {username}! Follow @ourpage first to unlock your free 42-page Growth Framework Guide 🚀",
    follow_comment_reply: "Almost there! Follow @ourpage and check your DMs for the free PDF guide 🚀",
    description: 'Captures hot leads by delivering an instant downloadable blueprint card when viewers comment.',
    comment_reply_message: 'Blueprint sent to your DMs! 📘 | Check your inbox for the download card! 🚀 | Guide sent! Check DMs ✨',
    dm_reply_message: "Hey {username}! 📘 Here is your copy of the 42-Page Growth Blueprint. Tap below to download immediately!",
    card_enabled: 1,
    card_title: '📘 42-Page Growth Blueprint & Action Checklist',
    card_subtitle: 'Step-by-step roadmap to scale your Instagram automations without paid ads.',
    card_image_url: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&auto=format&fit=crop&q=80',
    card_button_text: 'Download PDF (Free) 📥',
    card_button_url: 'https://airvix.com/demo/guide.pdf',
    stats: '96% Open Rate • 62% Download Rate',
  },
  {
    id: 'srv-consultation-booking',
    name: 'Free 15-Minute Strategy Call Booking',
    category: 'agency',
    categoryLabel: '💼 Agency & Services',
    badge: '📅 High Ticket Closer',
    trigger_keyword: 'AUDIT',
    match_mode: 'contains',
    action_type: 'comment',
    comment_reply_mode: 'both',
    require_follow: false,
    description: 'Turns reel viewers into booked appointments by sending an interactive Calendly card.',
    comment_reply_message: 'Calendar invite sent to your DMs! 📅 | Check your inbox to pick a slot! 📩 | Booking card sent! ✨',
    dm_reply_message: "Hey {username}! 🎯 Let's review your Instagram funnel on a complimentary 15-minute 1-on-1 strategy call.",
    card_enabled: 1,
    card_title: '📅 1-on-1 Growth Strategy Session',
    card_subtitle: 'Select a 15-minute opening on our VIP calendar this week.',
    card_image_url: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&auto=format&fit=crop&q=80',
    card_button_text: 'Select Date & Time 📅',
    card_button_url: 'https://airvix.com/demo/calendar',
    stats: '89% Open Rate • 34% Call Booked',
  }
];

module.exports = { DEFAULT_TEMPLATES };
